### ISSUE TITLE
TODO review

### ISSUE THREAD

**Issue by wtlyu** [ShanghaitechGeekPie/bookshelf#1]
Hi everyone, let's get this online by new year~

some todo list:
- [ ] add .gitignore and delete useless files. 
- [ ] remove devoter field in book.models.Book
- [ ] move django-env to a better way, perhaps using pipenv?
- [ ] add docker deploy script 
- [ ] clean-up naming styles :
```
class NameOfClass(object):
    every_field_name = None
    def every_function_name:
        pass
```

- [ ] try to deploy this on our server

@Dzhange @EricDiao @llk89 @philipxyc

**Comment by onelots** [comment]
👀👀👀
erf 
5 years later this project is exactly what I need but... 5 years is a loooong time in coding... Everything is deprecated as f**k 😮‍💨😮‍💨😮‍💨
